platform :ios, "7.0"
pod 'AFNetworking'
pod 'SSKeychain'
pod 'ARSafeJSON'
pod 'PeopleSwipeTableViewCell', :git => 'https://github.com/brunokoga/PeopleSwipeTableViewCell.git'
pod 'BKUIAdditions', :git => 'https://github.com/brunokoga/BKUIAdditions.git'
pod 'FormatterKit', '~> 1.2.0'

