platform :ios, "7.0"
pod 'AFNetworking', '2.0.0-RC2'
pod 'SSKeychain', :git => 'https://github.com/soffes/sskeychain.git'
pod 'ARSafeJSON'
pod 'PeopleSwipeTableViewCell', :git => 'https://github.com/brunokoga/PeopleSwipeTableViewCell.git'
pod 'BKUIAdditions', :git => 'https://github.com/brunokoga/BKUIAdditions.git'
pod 'FormatterKit', '~> 1.2.0'

